Add how to not run local instance of MongoDB to README.md
zodern/meteor-up pull request #499
Opened 2017-03-01 04:39 UTC by JohnAllen

This is buried in a closed issue so thought it would be helpful to have it in the README.

2017-03-01 14:21 UTC, zodern requested changes
Thanks. This is needed.

A couple things you could add:
- When you might want to use an external mongo instance. (Oplog, multiple servers running app, etc)
- List of companies offering MongoDB DBaaS

2017-03-01 14:21 UTC, zodern commented on README.md
> +instsance(s): `MONGO_URL: 'mongodb://some.other.ip.address:27017/dbname'`
Typo

2017-03-01 14:21 UTC, zodern commented on README.md
> +out the `mongo` section in your `mup.js` config file:
> simply comment out

Please change it to "simply remove or comment out"

Also, I'm not sure the example is needed. What is your opinion?

2017-03-01 14:21 UTC, zodern commented on README.md
> +- [Using External Mongo Instances](#accessing-the-database)
It links to the wrong section.

2017-03-01 14:28 UTC, shadowcodex commented on README.md
> +instsance(s): `MONGO_URL: 'mongodb://some.other.ip.address:27017/dbname'`
Denote that `MONGO_URL` is under the Meteor.ENV object.

2017-03-01 14:28 UTC, shadowcodex commented on README.md
> +out the `mongo` section in your `mup.js` config file:
Example is not needed IMO.

2017-03-04 15:39 UTC, JohnAllen commented on README.md
> +- [Using External Mongo Instances](#accessing-the-database)
Yeah I was doing this hastily as evidenced by the mistakes.

2017-03-07 21:24 UTC, shadowcodex commented
@JohnAllen are you able to make the requested changes?

2017-03-08 00:04 UTC, JohnAllen commented
Yes sure give me 36 hours. Been traveling.

On Mar 8, 2017 4:25 AM, "Shannon Duncan" <notifications@github.com> wrote:

> @JohnAllen <https://github.com/JohnAllen> are you able to make the
> requested changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zodern/meteor-up/pull/499#issuecomment-284864071>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ACq8AXNZimdpqarlQMfKZFsnxBts2ekcks5rjcsqgaJpZM4MPNoQ>
> .
>

2017-03-10 04:25 UTC, closed without merging