Use differents meteor settings file for each server
zodern/meteor-up pull request #876
Opened 2018-02-07 16:11 UTC by Farkal

This is really useful for me because I deploy to master server and secondary server, my main task need to be performed only on the master server so i need specific settings for the master server. If it can help somebody feel free to merge ;)
Example of my settings file: 

```
meteor: {
        ...
        servers: {
            one: {
                env: {
                    TOKEN: "popopo"
                }
            },
            two: {
                env: {
                    TOKEN: "papapa"
                },
                settings: "secondarySettings.json"
            }
        },
        ...
}
```

If nothing is defined it will use the default settings.json file ;)

2018-02-07 23:24 UTC, zodern requested changes
Thanks for working on this @Farkal.

It looks good. Please make 3 small changes, and then I can merge it.

- Fix the lint errors
- Change the base branch to `dev`. You can do this by clicking Edit next to the pull request title.
- Modify `getSettings` to use `getSettingsFromPath`.

2018-02-13 16:23 UTC, Farkal commented
It's done ;)
Please tell me if you need other adjustments.

2018-02-20 03:11 UTC, zodern commented
Looks good! Thank you.

2018-02-20 03:11 UTC, zodern approved these changes

2018-02-20 03:11 UTC, merged